---
layout: post
title: |-
  Well, if you’re selling sugar water or Spice Girl lunchboxes, then you really ought to get in on the action with ‘Sticker’ widgets. This side of the chart is very viral. So, find a 14 year old influential sneezer-user, encourage them to attach your widget to his/her social network profile and just stand back. If your brand and your widget rocks, then their friends will probably be bowled over by how cool they are and go copy them. Bingo - a new meme is born. The impressive Ori Soen from Musestorm had some interesting case studies on how his tech platform has helped brands do this kind of thing. If you’re not selling sugar water, and are in the more sober business of B2B, then think about how you can use all this widgety stuff to become a utility. To my mind, this is a big big opportunity for smart companies to pick apart the value of their products and services and get them to people in new ways. For example, if you’re a firm that needs to relay time sensitive, high value info to business customers, then build a Facebook or iGoogle widget and go give it to your most important users…. they’ll then pass it on to their friends, and hey presto, you have a new outlet for your brand/services/information. On the other hand, don’t even try to build a sticker style widget because the chances are your customers don’t think you’re THAT cool. (Think about it, if you hand out free badges at trade shows do you think people wear them when they get home!?). So… ‘Sticker’ widgets are fab in B2C where the budgets and the bets are big, the trends fast, and the payoffs large. ‘Utility’ widgets are great in B2B (and B2C) where the value of your content is high and your users are (probably) niche but extremely engaged and energized… because your stuff helps them do their jobs/live their life better and they’ll be grateful to get their hands on it and pass it on. In other words, sticker widgets may work for you if you can establish a ‘cool’ factor. Utility widgets will only work for you if you can establish a real value in your content. Either way, lazy marketers need not apply because it takes some figuring out. Whatever you do, IBM will never be cool, and I’ll never expect to get ‘utility’ style content from Coca-Cola. Anyways, that’s my view (thanks to Alex). What do you think? (Meantime, next up will be a post on what we as marketers need to do in order to make this stuff work effectively… inspired by another slam-dunk pitch from our friend Will McInnes of NixonMcInnes. Watch this space…) Tags: Advertising, B2B, Innovation, Marketing, Social Media, Web Marketing, Widgets
  Posted in Our Blog |
  AddThis Social Bookmark Button 3 Responses to ‘Widgety Goodness: Widgets and Social Media - WTF?!’ Subscribe to comments with RSS or TrackBack to ‘Widgety Goodness: Widgets and Social Media - WTF?!’. 1. Will McInnes said, on December 7th, 2007 at 11:20 am I agree that the ’stickers’ and ‘utiliities’ was actually a really neat, simple and helpful way to distinguish between the two. Also - loving the illustration Mr W, good use of ‘multimedia’! 2. Round-up: Widgety Goodness 2007 : Journalism.co.uk editors blog said, on December 7th, 2007 at 4:50 pm […] more thoughts on the event Steve Bowbrick has re-produced his speech, there’s a useful round-up by Roger Warner on the marketing side of the […] 3. agency technology marketing services and social networking | Velocity - the marketing acceleration agency for B2B technology companies said, on December 19th, 2007 at 5:50 pm […] to relay time sensitive, high value information to business customers via Facebook or iGoogle (see Roger’s recent blog on that), consider how most tech companies communicate with customers […] Have your say. Leave us a comment or two: Name (required) Email (will not be published) (required) Website Velocity Information Technology Marketing Blog RSS Feed RSS feeds Latest Blogs
  Tweakonomics: Why B2B Marketing Agency Retainers Suck This post hereby announces the death of the good old monthly agency retainer. Tweakonomics is what you should be using to pay for your marketing services - it’s what we advocate for all our clients. Let me explain…
  Read more blog entries Latest Papers
  The Holy Trinity of Technology Marketing Technology marketers (especially the ones who live in agencies) love to make marketing more complex than it really is…
  Read more papers Latest News
  ShipServ adds Velocity to web marketing effort ShipServ, the leading maritime e-marketplace, has chosen Velocity to execute a major website messaging and redesign project…
  Read more news Velocity Vectors Vents, vibes & voodoo
  sign up now … Agency Principals Doug Kessler
  Doug Kessler Roger Warner
  Roger Warner Stan Woods
  Stan Woods * Our clients
date: '2008-01-25T10:24:52-08:00'
tags: 
tumblr_url: http://alexhwilliams.tumblr.com/post/24661283/well-if-youre-selling-sugar-water-or-spice-girl
---
<blockquote>Well, if you’re selling sugar water or Spice Girl lunchboxes, then you really ought to get in on the action with ‘Sticker’ widgets. This side of the chart is very viral. So, find a 14 year old influential sneezer-user, encourage them to attach your widget to his/her social network profile and just stand back. If your brand and your widget rocks, then their friends will probably be bowled over by how cool they are and go copy them. Bingo - a new meme is born. The impressive Ori Soen from Musestorm had some interesting case studies on how his tech platform has helped brands do this kind of thing. If you’re not selling sugar water, and are in the more sober business of B2B, then think about how you can use all this widgety stuff to become a utility. To my mind, this is a big big opportunity for smart companies to pick apart the value of their products and services and get them to people in new ways. For example, if you’re a firm that needs to relay time sensitive, high value info to business customers, then build a Facebook or iGoogle widget and go give it to your most important users…. they’ll then pass it on to their friends, and hey presto, you have a new outlet for your brand/services/information. On the other hand, don’t even try to build a sticker style widget because the chances are your customers don’t think you’re THAT cool. (Think about it, if you hand out free badges at trade shows do you think people wear them when they get home!?). So… ‘Sticker’ widgets are fab in B2C where the budgets and the bets are big, the trends fast, and the payoffs large. ‘Utility’ widgets are great in B2B (and B2C) where the value of your content is high and your users are (probably) niche but extremely engaged and energized… because your stuff helps them do their jobs/live their life better and they’ll be grateful to get their hands on it and pass it on. In other words, sticker widgets may work for you if you can establish a ‘cool’ factor. Utility widgets will only work for you if you can establish a real value in your content. Either way, lazy marketers need not apply because it takes some figuring out. Whatever you do, IBM will never be cool, and I’ll never expect to get ‘utility’ style content from Coca-Cola. Anyways, that’s my view (thanks to Alex). What do you think? (Meantime, next up will be a post on what we as marketers need to do in order to make this stuff work effectively… inspired by another slam-dunk pitch from our friend Will McInnes of NixonMcInnes. Watch this space…) Tags: Advertising, B2B, Innovation, Marketing, Social Media, Web Marketing, Widgets<br/>
Posted in Our Blog |<br/>
AddThis Social Bookmark Button 3 Responses to &#8216;Widgety Goodness: Widgets and Social Media - WTF?!&#8217; Subscribe to comments with RSS or TrackBack to &#8216;Widgety Goodness: Widgets and Social Media - WTF?!&#8217;. 1. Will McInnes said, on December 7th, 2007 at 11:20 am I agree that the ’stickers’ and ‘utiliities’ was actually a really neat, simple and helpful way to distinguish between the two. Also - loving the illustration Mr W, good use of ‘multimedia’! 2. Round-up: Widgety Goodness 2007&#160;: Journalism.co.uk editors blog said, on December 7th, 2007 at 4:50&#160;pm […] more thoughts on the event Steve Bowbrick has re-produced his speech, there’s a useful round-up by Roger Warner on the marketing side of the […] 3. agency technology marketing services and social networking | Velocity - the marketing acceleration agency for B2B technology companies said, on December 19th, 2007 at 5:50&#160;pm […] to relay time sensitive, high value information to business customers via Facebook or iGoogle (see Roger’s recent blog on that), consider how most tech companies communicate with customers […] Have your say. Leave us a comment or two: Name (required) Email (will not be published) (required) Website Velocity Information Technology Marketing Blog RSS Feed RSS feeds Latest Blogs<br/>
Tweakonomics: Why B2B Marketing Agency Retainers Suck This post hereby announces the death of the good old monthly agency retainer. Tweakonomics is what you should be using to pay for your marketing services - it’s what we advocate for all our clients. Let me explain…<br/>
Read more blog entries Latest Papers<br/>
The Holy Trinity of Technology Marketing Technology marketers (especially the ones who live in agencies) love to make marketing more complex than it really is…<br/>
Read more papers Latest News<br/>
ShipServ adds Velocity to web marketing effort ShipServ, the leading maritime e-marketplace, has chosen Velocity to execute a major website messaging and redesign project…<br/>
Read more news Velocity Vectors Vents, vibes &amp; voodoo<br/>
sign up now &#8230; Agency Principals Doug Kessler<br/>
Doug Kessler Roger Warner<br/>
Roger Warner Stan Woods<br/>
Stan Woods * Our clients</blockquote>&#8212;<a href="http://www.velocitypartners.co.uk/2007/12/06/widgety-goodness-widgets-and-social-media-wtf/">Widgety Goodness: Widgets and Social Media - WTF?! | Velocity - the marketing acceleration agency for B2B technology companies</a>
