---
layout: post
title: These Rock Stars Could Have Done Better
date: '2008-10-14T23:19:00-07:00'
tags:
- featured artists coalition, f
- fac
- artist rights
- myspace music
- radiohead
- kate nash
- billy bragg
- copyright
- orchard
- the verve
tumblr_url: http://alexhwilliams.tumblr.com/post/54629704/these-rock-stars-could-have-done-better
---
<p><img src="http://featuredartistscoalition.com/fac_images/FAC_logo.jpg" align="text-top" height="49" width="194"/>The clashing worlds of art, business and technology met again earlier this month when a group of United Kingdom rock stars took the stage. This time they were not there to perform but to announce <a title="The Featured Artists Coalition" href="http://featuredartistscoalition.com/" id="wd9g">The Featured Artists Coalition</a>,(FAC) a group they organized to fight for copyright ownership, more bargaining power, and transparency in the dealings between the major labels and digital music distributors.</p>
<p>It&#8217;s exciting to see this development in the UK. One of my deepest interests is in artist rights. At Podcast Hotel I saw how powerful it can be when geeks and artists come together to talk, listen and share their experiences. It&#8217;s good stuff for the most part. I do have some criticism as it appears the effort is not set up to be sustainable. In some ways it looks like these rock stars came out for one show instead of creating a grasss roots strategy that could have artists and fans talking for months or even years to come.</p>
<p>FAC is a UK based group. Members include <a href="http://www.billybragg.co.uk/">Billy Bragg</a>, <a href="http://www.myspace.com/katenashmusic">Radiohead,</a> <a href="http://www.theverve.co.uk/">The Verve</a>, <a href="http://www.myspace.com/katenashmusic">Kate Nash</a> and a host of other rockers. From the coalition site:</p>
<blockquote>
<p>We want all artists to have more control of their music and a much fairer share of the profits it generates in the digital age. We speak with one voice to help artists strike a new bargain with record companies, digital distributors and others, and are campaigning for specific changes.</p>
</blockquote>
<p>Mike Duncliffe, writing in <a href="http://adage.com/songsforsoap/post?article_id=131550">Advertising Age</a>, does a decent job of explaining what the group hopes to achieve:</p>
<p style="margin-left: 40px;">According to a number of <a href="http://news.bbc.co.uk/2/hi/entertainment/7652143.stm" target="_blank" title="Link to reports on the BBC">reports on the BBC</a>, the group wants artists to keep the rights to the music they create and to have a greater say in how their songs are sold &#8212; and a bigger slice of the takings, naturally. At the moment, record labels normally own the rights to the music their artists make, though the artists often get &#8220;charged&#8221; back all the recording and marketing costs against their advances. Instead, the body is proposing that artists should own the rights but lease them back to labels, technology companies or anyone else for that matter, for up to 35 years, as happens in the US.</p>
<p>FAC has all the star power. The launch received extensive coverage.  <a title="Techdirt" href="http://wzus.ask.com/r?t=p&amp;d=us&amp;s=a&amp;c=blp&amp;l=dir&amp;o=0&amp;sv=0a30051c&amp;ip=47ec9b0a&amp;id=9EB58CC2C821BCD2E8E04B8A5B26B6D3&amp;q=featured+artists+coalition&amp;p=1&amp;qs=167&amp;ac=9&amp;g=418dTLOxiOfMfS&amp;en=blp&amp;io=0&amp;ep=&amp;eo=&amp;b=bs&amp;bc=&amp;br=&amp;tp=blr&amp;ec=10&amp;pt=Musicians%20Realize%20They%20Need%20Their%20Own%20Lobbying%20Group&amp;ex=&amp;url=&amp;u=http://techdirt.com/articles/20081005/2310512458.shtml" id="t2o.">Techdirt</a>, <a title="wired" href="http://blog.wired.com/music/2008/10/radiohead-other.html" id="i6i4">Wired</a>, <a title="Rolling Stone" href="http://www.rollingstone.com/rockdaily/index.php/2008/10/06/radiohead-lead-featured-artists-coalition-seek-greater-rights/" id="b_gs">Rolling Stone</a>, and music blogs such as <a title="Brooklyn Vegan" href="http://wzus.ask.com/r?t=p&amp;d=us&amp;s=a&amp;c=blp&amp;l=dir&amp;o=0&amp;sv=0a300522&amp;ip=47ec9b0a&amp;id=9EB58CC2C821BCD2E8E04B8A5B26B6D3&amp;q=featured+artists+coalition&amp;p=2&amp;qs=167&amp;ac=9&amp;g=790boBBZUOaj2O&amp;en=blp&amp;io=5&amp;ep=&amp;eo=&amp;b=bs&amp;bc=&amp;br=&amp;tp=blr&amp;ec=10&amp;pt=The%20Featured%20Artists%27%20Coalition%20want%20to%20take%20control&amp;ex=&amp;url=&amp;u=http://www.brooklynvegan.com/archives/2008/10/the_featured_ar.html" id="k9ee">Brooklyn Vegan</a> all covered FAC&#8217;s debut. I am afraid, though, it may not last. Really, these rock stars could have done better to keep the buzz going.</p>
<p><b>What&#8217;s Missing From The Featured Artists Coalition Campaign</b></p>
<p>Here&#8217;s my rub. FAC had a great launch with excellent coverage, but they are not set up to <b>sustain the buzz</b>. A few artists got the word out on their own, but I have not seen any signs of any grass roots marketing or concerted effort to network with each other and their fan bases.</p>
<p>FAC does not have a blog nor any RSS feeds. For perspective, I did use <a title="AideRSS" href="http://www.aiderss.com/" id="tlxm">AideRSS</a> to filter out the blog coverage. You may <a title="subscribe to the feed" href="http://feeds.feedburner.com/BloglinesSearchfeaturedArtistsCoalition-Aiderssall" id="sui2">subscribe to the feed</a> to see how the coverage unfolds. I <a title="archived the page" href="http://sqrl.it/?g0jpd" id="ka.a">archived the blog page</a> and have it scheduled to be saved using <a title="iterasi" href="http://www.iterasi.com/" id="r96q">iterasi</a>. We&#8217;ll see how much the coverage changes over the next month or so by comparing the search results to the archived search results for blog coverage that I captured yesterday.</p>
<p>It&#8217;s cool that FAC put a video on the front page of their site. Most startups don&#8217;t even do that. <b>But it&#8217;s a Quicktime video that can&#8217;t be embedded</b> into other web pages. <a href="http://profile.myspace.com/index.cfm?fuseaction=user.viewprofile&amp;friendid=22731731">Post War Years</a>, one of the bands featured in the video, took the most logical step. They put their <a href="http://www.youtube.com/watch?v=Kw_l4J-yQco">clip on YouTube</a>.  They&#8217;re the only band that resulted when I did a YouTube search for FAC. By the way, only one other result comes up on YouTube for FAC.</p>
<p>I discovered one Facebook page supporting FAC. It looks like a fan created it. The group has 23 members. I could not find a MySpace page for the coalition.</p>
<p>I can&#8217;t find one artist that features the coalition on their web site.</p>
<p>For example,<a title="Radiohead" href="http://www.radiohead.com/deadairspace/" id="swq4"> Radiohead</a> has no mention of FAC on their web site. One of their recent posts is from Tokyo, featuring a wild animation that some fan made. It kind of says networking to me. But wouldn&#8217;t it be effective to have some mention or icon about FAC? What is Radiohead&#8217;s philosophy about artist rights and why is it important to fans? This seems like a topic that should be discussed with fans, the greatest word of mouth network in the world. The ones who can have significant effects on the behaviors and business practices of labels everywhere.</p>
<p>Neither FAC nor any of the artists post logos or widgets that a blogger or fan could put on their site. So what if the coalition is just targeting artists? They could still use simple tools to reach out to people. All they have on their site is a form for artists to fill out. Maybe they have a campaign in waiting. That would be great. But it seems like they had the opportunity to create more connections and sustain the buzz. Instead, it looks like the buzz has stalled and will most likely not ignite unless they add some basic web infrastructure, sharing features and make a concerted effort to connect with fans.</p>
<p>As it stands, I am left feeling that this is just going to be one more effort that has big names behind it but not enough energy or interest in grass roots marketing for it to last. These are artists who break the rules all the time. I wonder if they really are a coalition and if they will band together to do something meaningful. I concur with <a title="Jason Gross of Pop Matters" href="http://www.popmatters.com/pm/post/64173/featured-artists-coalition-weird-al-taking-control/" id="l:io">Jason Gross of Pop Matters</a>, who writes:</p>
<p style="margin-left: 40px;">In theory, it’s a great idea and the labels have to play nice (or appear to) and there is the idea that there’s strength in numbers.  But it’s another thing to put it into practice.  How much are all of these artists really going to band together (so to speak)?  They have different outlooks, interests, motivations and schedules so it’s hard to imagine that other than symbolically, they’d all stay on the same page.  I wish ‘em luck and hope that more artists join and maybe they could even come up with their own bill of rights for musicians.</p>
<p><b>Why Does This Launch Concern Me So Much?</b></p>
<p>It&#8217;s an important and vital step for the artist community to receive its fair share in the new digital marketplace. By a glance at recent events, it is clear the artists could have been a stronger part of discussion with giants like MySpace Music. Independent labels are <a title="largely absent" href="http://musically.com/blog/2008/09/25/merlin-slams-lack-of-indies-as-myspace-music-launches/" id="giiq">largely absent</a> from the service. The Orchard is part of MySpace Music but they are definitely of second-tier status. <a title="Hypebot" href="http://hypebot.typepad.com/hypebot/2008/04/orchard-voices.html" id="h42t">Hypebot</a> obtained an email from CEO Greg Scholl that illustrates the inequality:</p>
<blockquote>
<p><a href="http://hypebot.typepad.com/.shared/image.html?/photos/uncategorized/2008/04/07/orchard.gif"><img alt="Orchard" title="Orchard" src="http://hypebot.typepad.com/hypebot/images/2008/04/07/orchard.gif" style="margin: 0px 5px 5px 0px; float: left;" border="0" height="60" width="80"/></a> &#8220;&#8230;it is unclear whether and how the equity the participating major labels received will be shared by them with their artists, or with the independent labels they simply distribute&#8230;To our understanding, independents have not been offered any equity.</p>
<p>"&#8230; Digital retail is fairer than physical brick-and-mortar retail ever was.  iTunes &#8230;helped to shift music industry dynamics towards a more level playing field&#8230;In that light, if reports are true, the apparent MySpace licensing approach is troubling.  It hearkens back to a time none of us wants to revisit &#8230; Where independent artists and labels were third-class citizens in the global music economy&#8230;"</p>
</blockquote>
<p>It&#8217;s also unclear what artists signed to the majors actually receive for their music appearing on the MySpace Music service. At the same time, the majors continue to increase their presence in the digital music space. Artists without proper representation may have no choice but to work with th labels if these giants have control over the major distribution channels.</p>
<p>Artists have historically not been a part of negotiations between the big four labels and digital music distributors like MySpace. FAC has a charter and what looks like a clear mission. All they need now is a campaign that can last. These days, you can&#8217;t really do that without some sort of grass roots strategy.</p>
<p><b>What Should That Grass Roots Strategy Look Like?</b></p>
<p>FAC should start a blog and develop a podcast. Fill the blog with conversations about the issues FAC seeks to address. Create a video podcast and use it as a tool to promote the artists&#8217; point of view. Interview artists but keep them short and sweet. Essentially, employ the basics of blog outreach.</p>
<p>Blog Outreach. FAC should be more proactive in reaching out to the most influential bloggers. If their goal is to uncover poor practices, these bloggers will be more than happy to have FAC as a source.</p>
<p>Embeds. FAC should use YouTube or a service like Viddler so people may embed the videos on their MySpace page, blog or any web page that permits it.</p>
<p>Widgets. FAC should hire a company like <a title="SplashCast" href="http://splashcastmedia.com/" id="gn:c">SplashCast</a> (disclaimer: I&#8217;m a shareholder) or use a service like <a title="Sprout Builder" href="http://sproutbuilder.com/" id="ktc9">Sprout Builder</a> to make a simple widget that artists may place on their site to show they support artist rights. Encourage fans to place the widget on their site.</p>
<p>Social Networks. FAC should establish a larger presence on MySpace and Facebook.</p>
<p>These rock stars have the star power. Now all they have to do is some basic grass roots marketing to connect all those millions of people who would be happy to support their cause.</p>
