---
layout: post
title: Bishop and Cook Shake Up The Seattle Tech News Scene
date: '2008-09-16T15:05:23-07:00'
tags: 
tumblr_url: http://alexhwilliams.tumblr.com/post/50457567/bishop-and-cook-shake-up-the-seattle-tech-news-scene
---
<p>I learned yesterday that Todd Bishop and John Cook were leaving the Seattle PI for the Pugety Sound Business Journal.  It struck me as a dramatic move that could have major effects on the Seattle tech publishing scene.</p>
<p>Today, Todd Bishop sent out an email, announcing their move:</p>
<blockquote>
<p>I&#8217;m excited to tell you about a new online technology news venture that my longtime colleague John Cook and I will be launching in Seattle in the coming weeks with the Puget Sound Business Journal.<br/><br/>Over time, we&#8217;re aiming to build the Seattle region&#8217;s leading technology news site. I&#8217;ll continue to report on the technology industry and write a blog about Microsoft on the new site, so I hope to stay in contact with you as I make the transition and re-establish my coverage. In the new role, I&#8217;ll be able to apply myself almost exclusively to online efforts. I&#8217;m looking forward to seeing what happens when I can focus even more on blogging and other forms of online reporting.<br/><br/> I&#8217;m also looking forward to working with John and the Business Journal to build this new venture. It&#8217;s going to be challenging and fun. Business Journal technology reporter Eric Engleman will be working closely with us, as well, so we&#8217;ve got a solid team in place. After we get up and running, we&#8217;ll also be hosting regular events around town, in conjunction with the site.<br/><br/> My six years at the Seattle P-I were invaluable to me. I feel fortunate to have worked with so many talented reporters and editors at the paper. The decision to leave wasn&#8217;t easy, but I&#8217;m ready and eager to take on this new adventure.<br/><br/> The best way to reach me for now is <a href="mailto:toddbishop@gmail.com" target="_blank">toddbishop@gmail.com</a> or 206-300-0265. You can also follow me on Twitter, at<a href="http://twitter.com/toddbishop" target="_blank"> twitter.com/toddbishop</a>. For now, we have a temporary holding page, <a href="http://www.pugetsoundbusinessjournal.com/tech" target="_blank"><a href="http://www.pugetsoundbusinessjournal.com/tech">www.pugetsoundbusinessjournal.com/tech</a></a>, where you can sign up to be notified when the new site launches, and to receive daily e-mail news alerts after we go live. The site will have its own name and a separate Web address that we&#8217;ll be announcing soon.<br/><br/> I&#8217;ll send my new contact info after we get settled at the new place. Thanks for your help and support, and thanks especially for reading and participating in my blog over the years. I&#8217;m looking forward to staying in touch.<br/><br/> Todd Bishop<br/><a href="mailto:toddbishop@gmail.com" target="_blank">toddbishop@gmail.com</a><br/>206-300-0265<br/><a href="http://twitter.com/toddbishop" target="_blank">twitter.com/toddbishop</a></p>
</blockquote>
