---
layout: post
title: 'A Resource For CloudCamp: Definitions For Cloud Computing'
date: '2009-06-30T14:01:00-07:00'
tags: 
tumblr_url: http://alexhwilliams.tumblr.com/post/133119527/a-resource-for-cloudcamp-definitions-for-cloud
---
<p><img src="http://www.cloudcamp.org/wp-content/themes/wicketpixie/images/logo_cloudcamp.gif" width="308" height="70"/></p>
<p>I wrote about defining cloud computing today on the <a href="http://bit.ly/msqVG">Tek-Tips</a> blog. Here&#8217;s a recap:</p>
<p>Several weeks ago, Reuven Cohen provided the Federal Government&#8217;s definitions for cloud computing. For the purposes of today&#8217;s <a href="http://bit.ly/T8Ll9">CloudCamp in Portland</a> and <a href="http://www.cloudcamp.com/columbus">Columbus</a>, I thought it might be helpful to provide the definitions that were developed with the participation from the private sector. </p>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><b>Key Characteristics:</b><br/></blockquote>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><br/>On-demand self-service. A consumer can unilaterally provision computing capabilities, such as server time and network storage, as needed without requiring human interaction with each service’s provider.<br/>Ubiquitous network access. Capabilities are available over the network and accessed through standard mechanisms that promote use by heterogeneous thin or thick client platforms (e.g., mobile phones, laptops, and PDAs).<br/>Location independent resource pooling. The provider’s computing resources are pooled to serve all consumers using a multi-tenant model, with different physical and virtual resources dynamically assigned and reassigned according to consumer demand. The customer generally has no control or knowledge over the exact location of the provided resources. Examples of resources include storage, processing, memory, network bandwidth, and virtual machines.<br/>Rapid elasticity. Capabilities can be rapidly and elastically provisioned to quickly scale up and rapidly released to quickly scale down. To the consumer, the capabilities available for rent often appear to be infinite and can be purchased in any quantity at any time.<br/>Pay per use. Capabilities are charged using a metered, fee-for-service, or advertising based billing model to promote optimization of resource use. Examples are measuring the storage, bandwidth, and computing resources consumed and charging for the number of active user accounts per month. Clouds within an organization accrue cost between business units and may or may not use actual currency.<br/>Note: Cloud software takes full advantage of the cloud paradigm by being service oriented with a focus on statelessness, low coupling, modularity, and semantic interoperability.</blockquote>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><br/></blockquote>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><b>Delivery Models:</b><br/></blockquote>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><br/>Cloud Software as a Service (SaaS). The capability provided to the consumer is to use the provider’s applications running on a cloud infrastructure and accessible from various client devices through a thin client interface such as a Web browser (e.g., web-based email). The consumer does not manage or control the underlying cloud infrastructure, network, servers, operating systems, storage, or even individual application capabilities, with the possible exception of limited user-specific application configuration settings.<br/>Cloud Platform as a Service (PaaS). The capability provided to the consumer is to deploy onto the cloud infrastructure consumer-created applications using programming languages and tools supported by the provider (e.g., java, python, .Net). The consumer does not manage or control the underlying cloud infrastructure, network, servers, operating systems, or storage, but the consumer has control over the deployed applications and possibly application hosting environment configurations.<br/>Cloud Infrastructure as a Service (IaaS). The capability provided to the consumer is to rent processing, storage, networks, and other fundamental computing resources where the consumer is able to deploy and run arbitrary software, which can include operating systems and applications. The consumer does not manage or control the underlying cloud infrastructure but has control over operating systems, storage, deployed applications, and possibly select networking components (e.g., firewalls, load balancers).</blockquote>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><br/></blockquote>
<blockquote style="margin: 0 0 0 40px; border: none; padding: 0px;"><b>Deployment Model:</b><br/><br/>Private cloud. The cloud infrastructure is owned or leased by a single organization and is operated solely for that organization.<br/>Community cloud. The cloud infrastructure is shared by several organizations and supports a specific community that has shared concerns (e.g., mission, security requirements, policy, and compliance considerations).<br/>Public cloud. The cloud infrastructure is owned by an organization selling cloud services to the general public or to a large industry group.<br/>Hybrid cloud. The cloud infrastructure is a composition of two or more clouds (internal, community, or public) that remain unique entities but are bound together by standardized or proprietary technology that enables data and application portability (e.g., cloud bursting).<br/>Each deployment model instance has one of two types: internal or external. Internal clouds reside within an organizations network security perimeter and external clouds reside outside the same perimeter.<br/></blockquote>
